"""
Mentixy — Real Aptitude Questions Seed
50 questions across 5 categories (TCS NQT / Infosys InfyTQ / Wipro NLTH patterns)
"""

APTITUDE_QUESTIONS = [
    # ═══ QUANTITATIVE APTITUDE (15) ═══
    {"topic": "profit_loss", "question_text": "A shopkeeper buys 80 articles for ₹2,400 and sells them at a profit of 16%. Find the selling price of one article.", "options": [{"key": "A", "text": "₹34.80"}, {"key": "B", "text": "₹30"}, {"key": "C", "text": "₹32"}, {"key": "D", "text": "₹36"}], "correct_answer": "A", "explanation": "CP per article = 2400/80 = ₹30. SP = 30 × 1.16 = ₹34.80", "shortcut": "CP × (100+P%)/100 = 30 × 116/100 = ₹34.80", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "profit_loss", "question_text": "A man sells two watches at ₹1,000 each. On one he gains 25% and on the other loses 25%. What is his gain or loss percent on the whole?", "options": [{"key": "A", "text": "6.25% loss"}, {"key": "B", "text": "No loss"}, {"key": "C", "text": "6.25% gain"}, {"key": "D", "text": "12.5% loss"}], "correct_answer": "A", "explanation": "When same SP with equal gain% and loss%, there is always a loss. Loss% = (common%)²/100 = 25²/100 = 6.25%", "shortcut": "Loss% = (X%)²/100 where X is the common percentage", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "quantitative"},
    {"topic": "time_work", "question_text": "A can do a piece of work in 10 days and B can do it in 15 days. In how many days will they finish together?", "options": [{"key": "A", "text": "5 days"}, {"key": "B", "text": "6 days"}, {"key": "C", "text": "7 days"}, {"key": "D", "text": "8 days"}], "correct_answer": "B", "explanation": "A's rate = 1/10, B's rate = 1/15. Together = 1/10 + 1/15 = 5/30 = 1/6. So 6 days.", "shortcut": "Combined days = (A×B)/(A+B) = (10×15)/(10+15) = 150/25 = 6", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "time_work", "question_text": "12 men can complete a work in 18 days. 6 additional men join after 6 days. How many more days will it take?", "options": [{"key": "A", "text": "8 days"}, {"key": "B", "text": "9 days"}, {"key": "C", "text": "10 days"}, {"key": "D", "text": "6 days"}], "correct_answer": "A", "explanation": "Total work = 12×18 = 216 man-days. Done in 6 days = 12×6 = 72. Remaining = 144. With 18 men: 144/18 = 8 days.", "shortcut": "Use man-days concept: Total = M×D, then divide remaining by new workforce", "difficulty": "medium", "source_pattern": "Wipro NLTH", "category": "quantitative"},
    {"topic": "percentage", "question_text": "If the price of sugar increases by 20%, by what percent must a family reduce consumption to keep expenditure the same?", "options": [{"key": "A", "text": "20%"}, {"key": "B", "text": "16.67%"}, {"key": "C", "text": "15%"}, {"key": "D", "text": "25%"}], "correct_answer": "B", "explanation": "Reduction = (Increase/(100+Increase))×100 = (20/120)×100 = 16.67%", "shortcut": "Reduction% = R/(100+R) × 100", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "ratio_proportion", "question_text": "Salaries of A and B are in the ratio 3:4. If each salary is increased by ₹4,000, the new ratio becomes 13:17. Find A's salary.", "options": [{"key": "A", "text": "₹12,000"}, {"key": "B", "text": "₹15,000"}, {"key": "C", "text": "₹18,000"}, {"key": "D", "text": "₹24,000"}], "correct_answer": "A", "explanation": "Let salaries be 3x and 4x. (3x+4000)/(4x+4000) = 13/17. Solving: 51x+68000 = 52x+52000. x=16000. A's salary = 3×4000 = ₹12,000", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "quantitative"},
    {"topic": "simple_interest", "question_text": "A sum of money becomes ₹6,600 in 2 years and ₹7,200 in 3 years at simple interest. Find the principal.", "options": [{"key": "A", "text": "₹5,000"}, {"key": "B", "text": "₹5,400"}, {"key": "C", "text": "₹6,000"}, {"key": "D", "text": "₹4,800"}], "correct_answer": "B", "explanation": "SI for 1 year = 7200-6600 = ₹600. SI for 2 years = ₹1200. Principal = 6600-1200 = ₹5,400", "shortcut": "Difference in amounts ÷ difference in years = SI per year", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "speed_distance", "question_text": "A train 150m long passes a pole in 15 seconds. Find the speed of the train in km/hr.", "options": [{"key": "A", "text": "36 km/hr"}, {"key": "B", "text": "40 km/hr"}, {"key": "C", "text": "45 km/hr"}, {"key": "D", "text": "30 km/hr"}], "correct_answer": "A", "explanation": "Speed = Distance/Time = 150/15 = 10 m/s = 10 × 18/5 = 36 km/hr", "shortcut": "m/s to km/hr: multiply by 18/5", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "speed_distance", "question_text": "Two trains 120m and 80m long are running in opposite directions at 42 km/hr and 30 km/hr respectively. Time to cross each other?", "options": [{"key": "A", "text": "8 seconds"}, {"key": "B", "text": "10 seconds"}, {"key": "C", "text": "12 seconds"}, {"key": "D", "text": "14 seconds"}], "correct_answer": "B", "explanation": "Total distance = 120+80 = 200m. Relative speed = 42+30 = 72 km/hr = 20 m/s. Time = 200/20 = 10s", "difficulty": "medium", "source_pattern": "Wipro NLTH", "category": "quantitative"},
    {"topic": "average", "question_text": "Average of 5 numbers is 20. If one number is excluded, the average becomes 18. Find the excluded number.", "options": [{"key": "A", "text": "28"}, {"key": "B", "text": "32"}, {"key": "C", "text": "24"}, {"key": "D", "text": "30"}], "correct_answer": "A", "explanation": "Sum of 5 = 100. Sum of 4 = 72. Excluded = 100-72 = 28", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "compound_interest", "question_text": "Find CI on ₹10,000 at 10% per annum for 2 years, compounded annually.", "options": [{"key": "A", "text": "₹2,000"}, {"key": "B", "text": "₹2,100"}, {"key": "C", "text": "₹2,200"}, {"key": "D", "text": "₹1,900"}], "correct_answer": "B", "explanation": "A = P(1+R/100)^n = 10000(1.1)^2 = 12,100. CI = 12100-10000 = ₹2,100", "difficulty": "easy", "source_pattern": "Infosys InfyTQ", "category": "quantitative"},
    {"topic": "pipes_cisterns", "question_text": "Pipe A fills a tank in 20 min, Pipe B in 30 min. If both are opened together with a drain pipe C that empties in 60 min, how long to fill?", "options": [{"key": "A", "text": "15 min"}, {"key": "B", "text": "18 min"}, {"key": "C", "text": "12 min"}, {"key": "D", "text": "20 min"}], "correct_answer": "A", "explanation": "Net rate = 1/20 + 1/30 - 1/60 = 3/60 + 2/60 - 1/60 = 4/60 = 1/15. Time = 15 min", "difficulty": "medium", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "ages", "question_text": "Father is 3 times as old as his son. After 10 years, he will be twice as old. What are their present ages?", "options": [{"key": "A", "text": "30 and 10"}, {"key": "B", "text": "36 and 12"}, {"key": "C", "text": "45 and 15"}, {"key": "D", "text": "24 and 8"}], "correct_answer": "A", "explanation": "Let son = x. Father = 3x. After 10: 3x+10 = 2(x+10). 3x+10 = 2x+20. x = 10. Father = 30.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},
    {"topic": "permutation", "question_text": "In how many ways can the letters of the word 'LEADER' be arranged?", "options": [{"key": "A", "text": "360"}, {"key": "B", "text": "720"}, {"key": "C", "text": "120"}, {"key": "D", "text": "240"}], "correct_answer": "A", "explanation": "LEADER has 6 letters with E repeated twice. Arrangements = 6!/2! = 720/2 = 360", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "quantitative"},
    {"topic": "probability", "question_text": "Two dice are thrown. What is the probability that the sum is 7?", "options": [{"key": "A", "text": "1/6"}, {"key": "B", "text": "5/36"}, {"key": "C", "text": "1/9"}, {"key": "D", "text": "7/36"}], "correct_answer": "A", "explanation": "Favorable: (1,6)(2,5)(3,4)(4,3)(5,2)(6,1) = 6 outcomes. Total = 36. P = 6/36 = 1/6", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "quantitative"},

    # ═══ LOGICAL REASONING (12) ═══
    {"topic": "number_series", "question_text": "What comes next in the series: 2, 6, 12, 20, 30, ?", "options": [{"key": "A", "text": "40"}, {"key": "B", "text": "42"}, {"key": "C", "text": "36"}, {"key": "D", "text": "38"}], "correct_answer": "B", "explanation": "Pattern: n(n+1). 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "number_series", "question_text": "Find the missing number: 3, 9, 27, 81, ?, 729", "options": [{"key": "A", "text": "162"}, {"key": "B", "text": "216"}, {"key": "C", "text": "243"}, {"key": "D", "text": "324"}], "correct_answer": "C", "explanation": "Geometric series: each number × 3. 81 × 3 = 243", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "coding_decoding", "question_text": "If COMPUTER is coded as DPNQVUFS, then how is MOBILE coded?", "options": [{"key": "A", "text": "NPCJMF"}, {"key": "B", "text": "NPCJOF"}, {"key": "C", "text": "NPCKNG"}, {"key": "D", "text": "NPCJMG"}], "correct_answer": "A", "explanation": "Each letter is shifted by +1. M→N, O→P, B→C, I→J, L→M, E→F = NPCJMF", "difficulty": "easy", "source_pattern": "Infosys InfyTQ", "category": "logical"},
    {"topic": "blood_relations", "question_text": "Pointing to a girl, Ravi said 'She is the daughter of my mother's only son.' How is the girl related to Ravi?", "options": [{"key": "A", "text": "Sister"}, {"key": "B", "text": "Daughter"}, {"key": "C", "text": "Niece"}, {"key": "D", "text": "Cousin"}], "correct_answer": "B", "explanation": "My mother's only son = Ravi himself. So the girl is Ravi's daughter.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "direction", "question_text": "Ram walks 10m south, turns left and walks 20m, turns left and walks 10m. Which direction is he from the start?", "options": [{"key": "A", "text": "North"}, {"key": "B", "text": "East"}, {"key": "C", "text": "West"}, {"key": "D", "text": "South"}], "correct_answer": "B", "explanation": "South 10m → left (East) 20m → left (North) 10m. He is now 20m East of starting point.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "seating", "question_text": "Five friends A, B, C, D, E sit in a row. A sits next to B. C sits at an end. D is not next to E. B sits in the middle. Who sits at the other end?", "options": [{"key": "A", "text": "A"}, {"key": "B", "text": "D"}, {"key": "C", "text": "E"}, {"key": "D", "text": "Cannot determine"}], "correct_answer": "C", "explanation": "B is in position 3. A is next to B (position 2 or 4). C is at one end. D not next to E. E must be at the other end.", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "logical"},
    {"topic": "syllogism", "question_text": "All cats are dogs. All dogs are birds. Conclusion I: All cats are birds. Conclusion II: All birds are cats.", "options": [{"key": "A", "text": "Only I follows"}, {"key": "B", "text": "Only II follows"}, {"key": "C", "text": "Both follow"}, {"key": "D", "text": "Neither follows"}], "correct_answer": "A", "explanation": "Cats ⊂ Dogs ⊂ Birds. So all cats are birds (I follows). But not all birds are cats (II doesn't follow).", "difficulty": "medium", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "clock", "question_text": "At what time between 3 and 4 o'clock are the hands of a clock together?", "options": [{"key": "A", "text": "3:16:21"}, {"key": "B", "text": "3:16:04"}, {"key": "C", "text": "3:15:00"}, {"key": "D", "text": "3:14:32"}], "correct_answer": "A", "explanation": "Hands together: 360/11 minutes after 3 = 16.36 min = 16 min 21.8 sec ≈ 3:16:21", "difficulty": "medium", "source_pattern": "Wipro NLTH", "category": "logical"},
    {"topic": "calendar", "question_text": "If January 1, 2023 is a Sunday, what day is March 1, 2023?", "options": [{"key": "A", "text": "Monday"}, {"key": "B", "text": "Tuesday"}, {"key": "C", "text": "Wednesday"}, {"key": "D", "text": "Thursday"}], "correct_answer": "C", "explanation": "Jan has 31 days, Feb has 28 days (2023 not leap). Total = 59 days. 59/7 = 8 weeks + 3 days. Sunday + 3 = Wednesday.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "venn_diagram", "question_text": "In a class of 60, 35 play cricket, 30 play football, 15 play both. How many play neither?", "options": [{"key": "A", "text": "10"}, {"key": "B", "text": "15"}, {"key": "C", "text": "5"}, {"key": "D", "text": "20"}], "correct_answer": "A", "explanation": "Union = 35+30-15 = 50. Neither = 60-50 = 10", "shortcut": "n(A∪B) = n(A)+n(B)-n(A∩B)", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},
    {"topic": "data_sufficiency", "question_text": "Is x positive? (I) x² > 0 (II) x³ > 0", "options": [{"key": "A", "text": "Statement I alone is sufficient"}, {"key": "B", "text": "Statement II alone is sufficient"}, {"key": "C", "text": "Both together needed"}, {"key": "D", "text": "Neither sufficient"}], "correct_answer": "B", "explanation": "x² > 0 is true for both positive and negative x (I not sufficient). x³ > 0 only if x > 0 (II sufficient).", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "logical"},
    {"topic": "pattern", "question_text": "What is the next term: A1Z, B2Y, C3X, D4W, ?", "options": [{"key": "A", "text": "E5V"}, {"key": "B", "text": "F5V"}, {"key": "C", "text": "E6V"}, {"key": "D", "text": "E5U"}], "correct_answer": "A", "explanation": "First letter: A→B→C→D→E (+1). Number: 1→2→3→4→5 (+1). Last letter: Z→Y→X→W→V (-1). Answer: E5V", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "logical"},

    # ═══ VERBAL ABILITY (10) ═══
    {"topic": "synonyms", "question_text": "Choose the synonym of 'AMBIGUOUS':", "options": [{"key": "A", "text": "Clear"}, {"key": "B", "text": "Vague"}, {"key": "C", "text": "Bright"}, {"key": "D", "text": "Certain"}], "correct_answer": "B", "explanation": "Ambiguous means unclear or having multiple meanings. Vague is the closest synonym.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "verbal"},
    {"topic": "antonyms", "question_text": "Choose the antonym of 'BENEVOLENT':", "options": [{"key": "A", "text": "Kind"}, {"key": "B", "text": "Generous"}, {"key": "C", "text": "Malevolent"}, {"key": "D", "text": "Helpful"}], "correct_answer": "C", "explanation": "Benevolent means kind/generous. Malevolent means wishing evil to others — the exact opposite.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "verbal"},
    {"topic": "sentence_correction", "question_text": "Identify the error: 'Each of the students have completed their assignments on time.'", "options": [{"key": "A", "text": "Each of"}, {"key": "B", "text": "have completed"}, {"key": "C", "text": "their assignments"}, {"key": "D", "text": "on time"}], "correct_answer": "B", "explanation": "'Each' is singular, so the verb should be 'has completed', not 'have completed'.", "difficulty": "easy", "source_pattern": "Infosys InfyTQ", "category": "verbal"},
    {"topic": "reading_comprehension", "question_text": "'The paradigm shift in AI has led to unprecedented automation.' What does 'paradigm shift' mean here?", "options": [{"key": "A", "text": "A minor change"}, {"key": "B", "text": "A fundamental change in approach"}, {"key": "C", "text": "A temporary trend"}, {"key": "D", "text": "A reversal"}], "correct_answer": "B", "explanation": "A paradigm shift refers to a fundamental change in approach or underlying assumptions.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "verbal"},
    {"topic": "fill_blanks", "question_text": "The manager's decision was _____ by the board, leading to its immediate implementation.", "options": [{"key": "A", "text": "ratified"}, {"key": "B", "text": "refuted"}, {"key": "C", "text": "rejected"}, {"key": "D", "text": "ridiculed"}], "correct_answer": "A", "explanation": "Ratified means officially approved. Context says it was implemented immediately, implying approval.", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "verbal"},
    {"topic": "idioms", "question_text": "What does 'burning the midnight oil' mean?", "options": [{"key": "A", "text": "Wasting resources"}, {"key": "B", "text": "Working late at night"}, {"key": "C", "text": "Starting a fire"}, {"key": "D", "text": "Being angry"}], "correct_answer": "B", "explanation": "'Burning the midnight oil' is an idiom meaning to work or study late into the night.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "verbal"},
    {"topic": "para_jumbles", "question_text": "Arrange: P-India is a diverse nation. Q-This diversity is its strength. R-With 28 states and 8 UTs. S-Each has unique culture and language.", "options": [{"key": "A", "text": "P-R-S-Q"}, {"key": "B", "text": "P-S-R-Q"}, {"key": "C", "text": "R-P-S-Q"}, {"key": "D", "text": "P-Q-R-S"}], "correct_answer": "A", "explanation": "P introduces topic → R elaborates structure → S describes each → Q concludes with strength.", "difficulty": "medium", "source_pattern": "Wipro NLTH", "category": "verbal"},
    {"topic": "one_word_substitution", "question_text": "A person who speaks many languages is called:", "options": [{"key": "A", "text": "Polyglot"}, {"key": "B", "text": "Polygraph"}, {"key": "C", "text": "Polymath"}, {"key": "D", "text": "Polychrome"}], "correct_answer": "A", "explanation": "Polyglot = person speaking many languages. Polymath = person of wide knowledge. Polygraph = lie detector.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "verbal"},
    {"topic": "active_passive", "question_text": "Change to passive: 'The company will launch the product next month.'", "options": [{"key": "A", "text": "The product will be launched by the company next month."}, {"key": "B", "text": "The product was launched by the company next month."}, {"key": "C", "text": "The product is being launched by the company next month."}, {"key": "D", "text": "The product had been launched by the company."}], "correct_answer": "A", "explanation": "Future tense passive: will + be + past participle. 'will be launched'.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "verbal"},
    {"topic": "cloze_test", "question_text": "Technology has _____ transformed how we communicate, making the world a smaller place.", "options": [{"key": "A", "text": "dramatically"}, {"key": "B", "text": "drastically"}, {"key": "C", "text": "dramatically"}, {"key": "D", "text": "fundamentally"}], "correct_answer": "D", "explanation": "While all options could fit, 'fundamentally' best describes a deep, core-level transformation in communication.", "difficulty": "medium", "source_pattern": "Infosys InfyTQ", "category": "verbal"},

    # ═══ DATA INTERPRETATION (8) ═══
    {"topic": "tables", "question_text": "Company revenue: 2020=₹40Cr, 2021=₹50Cr, 2022=₹65Cr, 2023=₹80Cr. What is the average growth rate?", "options": [{"key": "A", "text": "25%"}, {"key": "B", "text": "26.1%"}, {"key": "C", "text": "33.3%"}, {"key": "D", "text": "28%"}], "correct_answer": "B", "explanation": "Growth: 25%(2020-21) + 30%(2021-22) + 23.08%(2022-23) = 78.08/3 ≈ 26.03%", "difficulty": "medium", "source_pattern": "TCS NQT", "category": "data_interpretation"},
    {"topic": "pie_chart", "question_text": "Monthly expenses: Rent 30%, Food 25%, Transport 15%, Savings 20%, Others 10%. If total = ₹50,000, how much is Food + Transport?", "options": [{"key": "A", "text": "₹18,000"}, {"key": "B", "text": "₹20,000"}, {"key": "C", "text": "₹22,500"}, {"key": "D", "text": "₹15,000"}], "correct_answer": "B", "explanation": "Food(25%) + Transport(15%) = 40% of ₹50,000 = ₹20,000", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "data_interpretation"},
    {"topic": "bar_graph", "question_text": "Production: Mon=100, Tue=120, Wed=90, Thu=150, Fri=130. What % increase from Wed to Thu?", "options": [{"key": "A", "text": "66.67%"}, {"key": "B", "text": "60%"}, {"key": "C", "text": "50%"}, {"key": "D", "text": "75%"}], "correct_answer": "A", "explanation": "Increase = (150-90)/90 × 100 = 60/90 × 100 = 66.67%", "difficulty": "easy", "source_pattern": "Infosys InfyTQ", "category": "data_interpretation"},
    {"topic": "line_graph", "question_text": "Temperature readings: 6AM=18°C, 9AM=22°C, 12PM=30°C, 3PM=34°C, 6PM=28°C. Highest rise between consecutive readings?", "options": [{"key": "A", "text": "6AM-9AM"}, {"key": "B", "text": "9AM-12PM"}, {"key": "C", "text": "12PM-3PM"}, {"key": "D", "text": "3PM-6PM"}], "correct_answer": "B", "explanation": "Rises: 4°C(6-9), 8°C(9-12), 4°C(12-3), -6°C(3-6). Highest = 8°C between 9AM-12PM.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "data_interpretation"},
    {"topic": "caselets", "question_text": "A shop sold 200 items in Jan, 250 in Feb, 180 in Mar. Avg price was ₹500 in Jan, ₹450 in Feb, ₹600 in Mar. Which month had highest revenue?", "options": [{"key": "A", "text": "January"}, {"key": "B", "text": "February"}, {"key": "C", "text": "March"}, {"key": "D", "text": "Feb and Mar equal"}], "correct_answer": "B", "explanation": "Jan: 200×500=₹1,00,000. Feb: 250×450=₹1,12,500. Mar: 180×600=₹1,08,000. Feb is highest.", "difficulty": "medium", "source_pattern": "Wipro NLTH", "category": "data_interpretation"},

    # ═══ TECHNICAL APTITUDE (5) ═══
    {"topic": "output_tracing", "question_text": "What is the output?\n```python\nx = [1, 2, 3, 4, 5]\nprint(x[1:4])\n```", "options": [{"key": "A", "text": "[1, 2, 3, 4]"}, {"key": "B", "text": "[2, 3, 4]"}, {"key": "C", "text": "[2, 3, 4, 5]"}, {"key": "D", "text": "[1, 2, 3]"}], "correct_answer": "B", "explanation": "Python slicing x[1:4] returns elements at index 1, 2, 3 (end index excluded). So [2, 3, 4].", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "technical"},
    {"topic": "output_tracing", "question_text": "What is the output?\n```c\nint x = 5;\nprintf(\"%d\", x++ + ++x);\n```", "options": [{"key": "A", "text": "11"}, {"key": "B", "text": "12"}, {"key": "C", "text": "Undefined behavior"}, {"key": "D", "text": "10"}], "correct_answer": "C", "explanation": "Modifying a variable more than once between sequence points is undefined behavior in C/C++.", "difficulty": "hard", "source_pattern": "Infosys InfyTQ", "category": "technical"},
    {"topic": "algorithms", "question_text": "What is the time complexity of binary search?", "options": [{"key": "A", "text": "O(n)"}, {"key": "B", "text": "O(log n)"}, {"key": "C", "text": "O(n log n)"}, {"key": "D", "text": "O(1)"}], "correct_answer": "B", "explanation": "Binary search halves the search space each step, giving O(log n) time complexity.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "technical"},
    {"topic": "data_structures", "question_text": "Which data structure uses LIFO (Last In First Out)?", "options": [{"key": "A", "text": "Queue"}, {"key": "B", "text": "Stack"}, {"key": "C", "text": "Linked List"}, {"key": "D", "text": "Tree"}], "correct_answer": "B", "explanation": "Stack follows LIFO — the last element pushed is the first to be popped. Queue uses FIFO.", "difficulty": "easy", "source_pattern": "TCS NQT", "category": "technical"},
    {"topic": "sql", "question_text": "Which SQL clause is used to filter groups?", "options": [{"key": "A", "text": "WHERE"}, {"key": "B", "text": "HAVING"}, {"key": "C", "text": "GROUP BY"}, {"key": "D", "text": "ORDER BY"}], "correct_answer": "B", "explanation": "HAVING filters groups after GROUP BY. WHERE filters individual rows before grouping.", "difficulty": "easy", "source_pattern": "Wipro NLTH", "category": "technical"},
]


def seed_aptitude_questions(db):
    """Seed 50 aptitude questions into the database."""
    from models import Question
    # Check if aptitude questions already exist
    if db.query(Question).filter(Question.is_aptitude_question == True).count() > 0:
        return 0
    count = 0
    for q in APTITUDE_QUESTIONS:
        db.add(Question(
            question_type="aptitude",
            category=q["category"],
            question_text=q["question_text"],
            options=q["options"],
            correct_answer=q["correct_answer"],
            explanation=q.get("explanation"),
            tags=[q.get("topic", ""), q.get("source_pattern", "")],
            is_aptitude_question=True,
            is_active=True,
        ))
        count += 1
    db.commit()
    return count

