/**
 * Mentixy — Route Constants
 */
export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
    ONBOARDING: '/onboarding',
    DASHBOARD: '/dashboard',
    ASSESSMENT: '/assessment',
    RESULTS: '/results',
    CAREER: (slug: string) => `/careers/${slug}`,
    CAREERS: '/careers',
    ROADMAP: '/learn',
    CODING: '/practice',
    CODING_PROBLEM: (slug: string) => `/practice/${slug}`,
    JOBS: '/jobs',
    INTERNSHIPS: '/internships',
    CHAT: '/chat',
    CHALLENGES: '/challenges',
    NETWORK: '/network',
    COMPANY: (slug: string) => `/company-intel/${slug}`,
    COMPANIES: '/company-intel',
    RESUME: '/resume',
    CAMPUS: '/campus',
    SETTINGS: '/settings',
    PROFILE: (username: string) => `/u/${username}`,
    NOTIFICATIONS: '/notifications',
    MARKET: '/skill-market',
    APTITUDE: '/aptitude',
    SCORE: '/score',
    DAILY: '/daily',
    ANALYTICS: '/analytics',
    TRACKER: '/tracker',
    COLLEGE_ROI: '/college-roi',
    SIDE_INCOME: '/side-income',
    COURSES: '/courses',
    SKILLS: '/skills',
    COMMUNITY: '/community',
    LEADERBOARD: '/leaderboard',
    ADMIN: '/admin',
    SIMULATOR: '/simulator',
    NEGOTIATE: '/negotiate',
    FIRST_90_DAYS: '/first-90-days',
    PARENT: '/parent',
    PEOPLE_LIKE_YOU: '/people-like-you',
    ROADMAP_PAGE: '/roadmap',
    RESULTS_PAGE: '/results',
    VERIFY: (hash: string) => `/verify/${hash}`,
    CAREER_DETAIL: (slug: string) => `/career/${slug}`,
    COMPANY_DETAIL: (slug: string) => `/company/${slug}`,
} as const;

export const AUTH_ROUTES = [ROUTES.LOGIN, ROUTES.SIGNUP, ROUTES.ONBOARDING];
export const PUBLIC_ROUTES = [ROUTES.HOME, ROUTES.LOGIN, ROUTES.SIGNUP];
